# First native whole-save prefix: independent audit

No concrete custody or tested-prefix contradiction found. This is a read-only audit of closed native job35239, not a new engine run or L3 acceptance. Root released the current source/art freeze afterward; this audit uses only the job’s frozen originals.

The original [metadata](a1-l3-full-parent-candidate-native1.json) SHA256 `7cc93fd782d4f839c6caf80b1d78ce012fb9489d1e186d997bf10bbdef96deb6` records HEAD `b1d0a04ee61a0ce96b630cbc33810696842164a8`, API37/publication `36090c9d83bb762b14310aa22978f1b31469551f`, UTC `2026-10-09T02:56:57.097252+00:00` through `03:01:39.204176+00:00`, and literal exit0. Independently enumerated all383 frozen files: physical membership equals the declared383-path set, every SHA256 matches, and the recorder’s post-execution mismatch list is empty. HEAD descends the exact37 publication. Frozen Game, Player, Shell, Level, Attempts, SaveStore, ExactJson and Scheduler bytes also equal their immutable37 blobs. This verifies the selected literal/dynamic TEST closure, not a complete import/resource graph.

The complete210186-byte [log](a1-l3-full-parent-candidate-native1.log) SHA256 `ca2ce93e0eed8ab4ad457b2137f80523ae553f9ad9f5f47746f0e74c87a16023` has the native `665 checks/0 failures;10 recognizer swipes/3 ordinary primaries` summary and zero ERROR, SCRIPT ERROR, WARNING, parse-error or ObjectDB-leak lines. The original [report](l3-full-aggregate-fixture-281693981.json) SHA256 `db389bbbba460dfc145a3dc200bafb3d0ee4450b3c0586bb303d0e7819125783` agrees, with literal integer counts and10 receipts. The [root join](a1-l3-full-parent-candidate-native1-report-join.json) SHA256 `b226997940f2c31cc154f2bcea283bc2e309cc24841538a4e7aef6972f28c610` is a later qualification: the original summary does not name the report. Independently found exactly one matching `l3-full-aggregate-fixture-*.json` in the recorder UTC window (actual mtime `03:01:38.889576+00:00`), and frozen fixture510–515 constructs that basename. No original filename pointer is invented.

## Exact native state and input

Decoded the retained ExactJson tagged representation only for inspection, and compared its tagged local value directly before numeric decoding: the direct quiet-recapture local is exactly the saved local, preserving float64 tags/bytes. Saved whole wire SHA256 `80aeda1f3fad6eb566fe1b65915128822b55335ed6c98f4618e854d3d9fae9dd` equals receipt7. It contains the nine closed local roots/all19 actors, beat1/active, prefix `[umbrella-grove]`,3 genuine dead Umbrella actors/3 living Breathing actors/13 full-HP pristine dormant future actors, one native `breathing-1/threat-4` cycle1 Warning, and one exact six-key accepted frame with the full action_escape proof. Scheduler clock is `0.9500000000000013`; native lease start is `0.933333333333335`. Breathing2 retains genuine approach_driving/nonzero planar velocity, so the restored unit is not merely an all-stationary mock. Breathing Field/Consumer exist; Field is available/generation0/spent_ids empty and all later fields/consumers remain null. No active/depleted spore episode is tested here.

The true earlier checkpoint is beat1/approach with3 dead/16 dormant, no fields/consumers/frames and no reservations/profile. Both snapshots retain Player HP100/shells2, grounded stationary poses and their actual clocks/history. Retry restores the earlier primary cooldown `0.2833333333333333`, rather than inventing a fresh ready clock. Full resources alone do not prove preservation of an injured/zero-shell Player; neither is claimed.

Receipt9 contains13 consecutive world records,10 dashes and3 ordinary primaries, plus13 actual recognizer observations. Every primary hit1/damage20; no blast record. Each swipe observation deliberately has accepted=false/prior world sequence, while its real completed dash is the movement authority; all thirteen pairs satisfy the unchanged native ordering grammar. Frozen [Game402–463](a1-l3-full-parent-candidate-native1-source/scripts/game.gd#L402), inherited route717–725 and actual ScreenTouch/Drag/release helpers establish this distinction. No telemetry defect or failed-movement inference follows from accepted=false. GUI Resume is separately checked to consume press/release without adding a world action or changing the release anchor.

## Construction, refusal and durable public boundaries

Read frozen [fixture308–446](a1-l3-full-parent-candidate-native1-source/tests/acts/act1/a1_l3_full_parent_candidate.gd#L308), [Actor198–264](a1-l3-full-parent-candidate-native1-source/scripts/acts/act1/mushroom_selenite.gd#L198), full-parent113–199/388–515/812–842, RouteCodec123–222, and native Shell611–710. The one-shot constructor requires the real paused nonplayable candidate, actual retained body/art/Player/Scheduler/resource/world aliases and pure seven-key prefix entitlement. It only exposes fresh living native recipients; saved HP/role/pose/clock/sample/stamp are not assigned by construction or ordinary activate/begin replay. Future actors stay dormant. Native Field/Protocol/Consumer bindings derive from those real recipients before full pure saved-Player/actor/Scheduler/history/resource validation. Exact quiet commit is Player→Fields→physical actors→Scheduler→actor exchanges/stamps→Consumers→owned metadata/frame/cache/art; the full wrapper prevents a void-hook commit failure from falsely becoming installable. Complete current optics are checked only after this quiet unit with the actual candidate camera/HUD/Hero22, not a donor alias or saved-body seed.

The actual665/0 result exercises five separately copied malformed cases: foreign source lease, Scheduler clock+.5, earlier dead HP1, future court dormancy false, and unearned completed prefix. Each is rejected by both public local+saved-Player preflight and the real Attempts validator (whose native snapshot_validator is Shell._snapshot_problem), before model commit. Each complete donor receipt remains equal: native identities/full snapshot/UI and objective/input/camera/attempts/actions/events/primary+backup disk. Error diagnostics such as Attempts.last_error or Shell.campaign_error are intentionally not donor state. The separate copied focus+100 case reaches the post-quiet optical gate, rejects/disposes its real candidate, empties validation candidates and preserves that same donor receipt.

Direct canonical `_prepare` tests pristine19 plus the six entitled prior/current recipients before commit; repeated pure validation leaves it and the donor unchanged. Quiet signal witnesses cover Scheduler invalidation, Player world_action/fired/died/action_resolved/equipment_changed, all actor state/defeat/hit/cue and installed Field/Consumer signals: recorded delta0. Candidate live capture/progress/finish are refused before commit, and live capture remains refused while nonplayable after quiet restoration. Exact recapture, actual saved Player/camera/actor lifecycle and disposed-recipient checks pass; canonical `_prepare_snapshot` independently repeats the true construction/prevalidate/commit/optical path.

Fresh second Shell begins at the real Title with NULL Player/level, loads native format2 disk, and public Continue installs distinct native19 identities with exact later whole wire, actual same-world aliases and protected earlier checkpoint; it does not change the paused donor. Its disposal is checked. Public Retry then installs distinct earlier native identities with exact earlier wire/resources/3 dead/16 dormant/no later environment and no L3 completion. Registry/TEST predecessor metadata and their public handoff are expressly setup only; no L1/L2 gameplay is credited. The frozen fixture’s CampaignMenu override retains checkpoint-save drains, one original2-native complete-current-view/deferred-pause window, real GUI Resume, exact disk payload/model equality and the original bounded ten-minute watchdog.

Cleanup disconnects observers, disposes any remaining candidate/fresh shell, clears native audio, frees Game, restores FPS/audio settings and removes the isolated test save directory; the complete log is clean. This selected fixture does not add the normal full-route physical-contact cleanup assertions. Original metadata/log/report/join and all frozen sources were left unchanged.

Limits remain: only the earned Umbrella clear→Breathing Warning prefix, neutral/Standard starter gear; no all19 defeat/full-route/completion/contact, later-room candidate, active/depleted repulsion save, injured/zero-ammo save, legal-kit/profile matrix, PNG/art optical audit, native-focus/human/performance or production campaign/L3 acceptance. This run supplies no renderer captures; PNGs inside its source closure are source assets. No current source/art changes are retroactively credited.
