# Focused save-policy independent review

PRIVATE new note only, read-only review at HEAD `5f526975199d595a73d1b699bd2c7b143325d942`, Shared39. No engine/parser/import, tracked edits, new test proposal or frozen-bundle changes. This follows Root's latest instruction to avoid an unnecessary saved test; the intermediate idea of a short representative fixture was not implemented.

[1518a40b-ac4d-4969-b1d9-f34813c4ff4a-UPDATE.json](</Users/howardchen/Documents/ChatGPT/video game idea/.cinder/agent-chat/cinder-campaign/integration/messages/1518a40b-ac4d-4969-b1d9-f34813c4ff4a-UPDATE.json>) immediately removes full-route/defeat-all/exit playthrough gates, permits disclosed legitimate representative test setups and keeps runtime/content/ownership contracts. SHA `833f1bd98e23d32177bfb56e326d66d729dc8b1fdcec230ad25976a52d6478e8`. [337a812c-9bb1-455b-a826-adb9259cfed9-UPDATE.json](</Users/howardchen/Documents/ChatGPT/video game idea/.cinder/agent-chat/cinder-campaign/integration/messages/337a812c-9bb1-455b-a826-adb9259cfed9-UPDATE.json>) explicitly maps A1-L3's473 mechanics/513 component visuals/**665 Save+Retry**/159 floor/325 fresh GUI as reusable focused evidence; latest cap needs a brief current visual. Published policy child `027dfa16e4c215ab1cc9f86bd0e4792088d16446` is documentation only, no runtime/native credit. Message SHA `29f345b0770a3f5790b7dde05cac1f5b3b3548e28f926f7aa407658f9ef0cb74`.

## Recommendation

Keep frozen358 unpromoted and immutable; it is **not needed as an acceptance gate**. All37 current source pins still match, and its exact SHA remains `ecc6ff35b734de1fe63ea74a3d1f826626e7d5957a96848a2fb38efa8eed02b4`. Its genuine first-two-room earning is optional additional evidence; it cannot close a supposed durable Save/Continue/Retry gap because it explicitly excludes those operations. See [.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:72](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:72>) (route prefix), [.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:176](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:176>) (direct native `_prepare`/quiet recipient only), [.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:350](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/.cinder/a1-l3-earned-crossed-save-candidate/a1_l3_relocated_crossed_saved_unit.gd.txt:350>) (honest noncampaign scope). Do not create a replacement short saved test without an actual affected defect/gap. Root's existing focused evidence plus the current visual/production-entry work is the frontier.

## Exactly what665 establishes and can be reused

Original `.cinder/a1-l3-full-parent-candidate-native1.json` SHA `7cc93fd782d4f839c6caf80b1d78ce012fb9489d1e186d997bf10bbdef96deb6` records closed exit0, Shared37/head `b1d0a04ee61a0ce96b630cbc33810696842164a8`,383 frozen originals and no post-execution mismatch. Joined report `.cinder/l3-full-aggregate-fixture-281693981.json` SHA `db389bbbba460dfc145a3dc200bafb3d0ee4450b3c0586bb303d0e7819125783` is665/0,10 genuine swipes/3 ordinary primaries. It used disclosed TEST predecessor metadata, then actual umbrella clear/Breathing Warning, full19 exact unit/candidate, malformed atomic rejection, actual fresh disk Title Continue and protected earlier Retry. Historical neutral Standard HP100/shells2/generation0 scope remains; it is not an injured/zero-ammo or active/depleted-field snapshot pass.

Directly compared preserved383-source originals against current physical bytes: the following remain identical, not inferred from commit ancestry:
| Unchanged executed/current input | SHA-256 |
| --- | --- |
| `scripts/acts/act1/mushroom_caverns_full.gd` | `e6669c37647542b6225dbcfabd4e2ec99a4085bf77e3d8ef1b757fdf176956d5` |
| `scripts/acts/act1/mushroom_caverns_route_codec.gd` | `4a3c7071a91aa0a0d441396b4b34c6141b0df005fe3f3b729a0e6668b2ea2fa0` |
| `scripts/acts/act1/mushroom_selenite.gd` | `24749ae5a7dd4334aac643fffac603570040098a3970929561e53a4f86e51576` |
| `scripts/campaign/shell.gd` | `01440e201b83334793cc0e607c7b2f1777d02833f6cdb2c539bad30bce9dd07a` |
| `scripts/campaign/level.gd` | `1989a4170b68329afd6f49c5698b23aa96722883698ccacf32f905619539010d` |
| `scripts/combat/threat_scheduler.gd` | `9b11730b4041dfb73a20e97bda0c72854a89af1ab79809fb3d8449fec624ae79` |
| `scripts/player.gd` | `8e4dfeb2c285f1d786ec3268bdaf5efbc70b3b0f4b2473b2870e0566a88e4743` |
| `scenes/acts/act1/a1_l3_full.tscn` | `2c53526ff33cfb8b61bfcd6205a565bff2e37f75e24976e15351407cccfff556` |

The existing runtime/fixture methods demonstrate actual full unit transport, prevalidate-before-commit, real distinct recipient, quiet Player→Level, current saved-focus/HUD gate, donor/UI/disk protection and disposal; [tests/acts/act1/a1_l3_full_parent_candidate.gd:334](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/tests/acts/act1/a1_l3_full_parent_candidate.gd:334>), [tests/acts/act1/a1_l3_full_parent_candidate.gd:425](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/tests/acts/act1/a1_l3_full_parent_candidate.gd:425>), [tests/acts/act1/a1_l3_full_parent_candidate.gd:102](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/tests/acts/act1/a1_l3_full_parent_candidate.gd:102>). Runtime Shell still routes paused exact capture and candidate restore through its real model; [scripts/campaign/shell.gd:392](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/campaign/shell.gd:392>), [scripts/campaign/shell.gd:611](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/campaign/shell.gd:611>), [scripts/campaign/shell.gd:642](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/campaign/shell.gd:642>). Those unchanged lifecycle/atomicity/retry guarantees remain reusable under the explicit Integration mapping. This does **not** transform the original665 artifact into a native run on today's art/world or a proof of every possible later room. No new all-room or gear test follows solely from that distinction.

## Exact geometry/material deltas and boundaries

- Against665, Route differs only by `CrossedRightStalk` origin `(5.6,0,-18)`→`(5.6,0,-16)` at [scripts/acts/act1/mushroom_caverns_route.gd:76](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/acts/act1/mushroom_caverns_route.gd:76>). Actual physical BOX, full painted surface and offset cap use the same table; size/role/controllers/timing/cast/progression/save schema are unchanged. Thus the native static collision fingerprint **does change even in an earlier-room save**, because every stalk exists from initial construction. Current Codec [scripts/acts/act1/mushroom_caverns_route_codec.gd:143](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/acts/act1/mushroom_caverns_route_codec.gd:143>) deliberately compares exact saved and actual-world collision bytes before commit. Do not claim an original pre-relocation wire now loads unchanged; a mismatch must reject rather than invent/translate collision data. This is the existing strict invariant, not a source-proven lifecycle bug or reason to repeat two rooms.
- Grotto Art since665 added the presentation-only quiet floor overlay, plus retained alpha/AA/blend/depth properties. That distinct affected resource/quiet-candidate scope was already exercised by159/0 on its original2c428ad bytes. Current cap's additional delta is exactly `_vertex_material(true)`→`false` for `FacetedPaintedCap`, [scripts/acts/act1/mushroom_grotto_art.gd:155](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/acts/act1/mushroom_grotto_art.gd:155>): remove RockPaint multiplication while retaining all native mesh vertices/UV/envelope/gills, parent frame, depth and collision. This later cap change has no saved HP/clock/lease/field/progress/codec fields. Material identity/texture/settings still bind strictly at [scripts/acts/act1/mushroom_grotto_art.gd:299](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/acts/act1/mushroom_grotto_art.gd:299>) and [scripts/acts/act1/mushroom_grotto_art.gd:334](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/acts/act1/mushroom_grotto_art.gd:334>); null cap texture is a newly constructed retained value, not a validator exception. Current source Art221ceb3f/manifestfcafea9c are not relabelled as159 pixels or bindings.
- Therefore **no new durable Save/Retry defect is established by either delta**. The moved physical world makes exact historical save compatibility intentionally conditional; the cap material itself needs a brief current visual, as Integration explicitly states. A current pristine positive native capture/quiet optical check or existing floor-resource scope may be useful if Root's actual production assembly reveals a concrete binding problem; it does not require a fresh long route or the frozen358. No result is claimed for such an optional check here.

## Production alias and remaining honest scope

Root's contemplated `scenes/acts/act1/a1_l3.tscn` alias is not yet assumed by this review. Existing fixture [tests/acts/act1/a1_l3_full_parent_candidate.gd:10](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/tests/acts/act1/a1_l3_full_parent_candidate.gd:10>) explicitly loads `a1_l3_full.tscn`; a future alias's actual scene identity/loading deserves a small targeted entry/brief-view check once promoted. Full producer/codec/physics reuse remains possible, but old saved `scene_path` is not silently interchangeable: [scripts/campaign/level.gd:371](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/campaign/level.gd:371>) checks exact actual level scene identity. If a focused future fixture uses the alias, a minimal explicit scene-path hook/whitelist and source pin update is appropriate; no private Shell/candidate recipe or fabricated old envelope. Root owns any promotion/testing. Existing public TEST scene configuration at [scripts/campaign/shell.gd:39](</Users/howardchen/.codex/worktrees/campaign-act1/video game idea/scripts/campaign/shell.gd:39>) remains setup, never canonical acceptance.

No requirement is added for Crossed kills, all19 defeat, earned exit, all kits,15-minute renderer replay or injured/spent-field matrices. The original1154/1 capture continuation and other old route failures retain exact historical labels and source diagnosis; they are not acceptance gates. Current cap visual, actual production alias loading/registration when created, and any independently demonstrated concrete lifecycle failure are the only justified next focused questions in this narrow review.
